blank_issues_enabled: false
contact_links:
  - name: 🚀 Blockfield Launcher
    url: https://github.com/netherg-io/blockfield-launcher-releases/releases/latest
    about: Проблемы самого лаунчера и загрузка последней версии
